### ISSUE TITLE
UpdateMergedOptionsFromMicrosoftIdentityOptions Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by RbsTechOnline** [AzureAD/microsoft-identity-web#1957]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

1.25.5

### Web app

Sign-in users and call web APIs

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

Not Applicable

### Description

Fist call to web api is causing an error an 

`Collection was modified; enumeration operation may not execute`

in 

`internal static void UpdateMergedOptionsFromMicrosoftIdentityOptions(MicrosoftIdentityOptions microsoftIdentityOptions, MergedOptions mergedOptions)`

Seemingly at

`if (!mergedOptions.ClaimActions.Contains(claimAction))`

### Reproduction steps

This is just a preliminary assessment. Can work towards a full repro if needed

### Error message

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at Microsoft.Identity.Web.MergedOptions.UpdateMergedOptionsFromMicrosoftIdentityOptions(MicrosoftIdentityOptions microsoftIdentityOptions, MergedOptions mergedOptions)
   at Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderExtensions.<>c__DisplayClass3_0.<AddMicrosoftIdentityWebApiImplementation>b__0(JwtBearerOptions options, IServiceProvider serviceProvider, IOptionsMonitor`1 mergedOptionsMonitor, IOptionsMonitor`1 msIdOptionsMonitor, IOptions`1 msIdOptions)
   at Microsoft.Extensions.Options.ConfigureNamedOptions`5.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsCache`1.<>c__3`1.<GetOrAdd>b__3_0(String name, ValueTuple`2 arg)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd[TArg](String name, Func`3 createOptions, TArg factoryArgument)
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### Relevant code snippets

```csharp

  builder.Services
         .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
         .AddMicrosoftIdentityWebApi(builder.Configuration.GetSection("IdentityPortal"), "Portal");

  ...

  builder.Services.AddAuthorization();

  ...

  app.UseAuthentication();
  app.UseAuthorization();

  ...

  Controller

  [Authorize(AuthenticationSchemes = "Portal"),RequiredScope("Api.ReadWrite")]
```

### Expected behavior

I am not really sure where the problem is originating from, or what might be the cause of it. 

My questions is, is this known issue, and I am missing something simple?

**Comment by jmprieur** [comment]
Thanks @RbsTechOnline
is it an option for you to try out Microsoft.Identity.Web 2.0.5-preview ?
We believe this is fixed there.

**Comment by RbsTechOnline** [comment]
@jmprieur it sure is, ill try and report back. Thanks

**Comment by jmprieur** [comment]
Thanks @RbsTechOnline 
cc: @jennyf19

**Comment by bartdebever** [comment]
Currently running into the same issue, tried the 2.0.5-preview package but the same exception still occurs

**Comment by jennyf19** [comment]
@bartdebever Does the error happen in .NET 6 as well?

**Comment by jennyf19** [comment]
@RbsTechOnline and @bartdebever I'm not able to repro on .NET 6 or .NET 7. can you provide exact repro steps, I tried to mimic what @RbsTechOnline did by replicating what he has provided above, but could be missing a key part. I'm running our web app calls web API calls graph sample.

**Comment by bartdebever** [comment]
> @bartdebever Does the error happen in .NET 6 as well?

This used to work within .NET 6, same package version. I'll attempt to reproduce the issue myself within a new project on GitHub as I, unfortunately, can't share the source for the actual project.

**Comment by RbsTechOnline** [comment]
Hi @jennyf19 I can verify the same error in `Microsoft.Identity.Web 2.0.5-preview`

I do note the stack trace is slightly different, 

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at Microsoft.Identity.Web.MergedOptions.UpdateMergedOptionsFromMicrosoftIdentityOptions(MicrosoftIdentityOptions microsoftIdentityOptions, MergedOptions mergedOptions)
   at Microsoft.Identity.Web.MicrosoftIdentityOptionsMerger.PostConfigure(String name, MicrosoftIdentityOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsCache`1.<>c__3`1.<GetOrAdd>b__3_0(String name, ValueTuple`2 arg)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd[TArg](String name, Func`3 createOptions, TArg factoryArgument)
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   at Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderExtensions.<>c__DisplayClass3_0.<AddMicrosoftIdentityWebApiImplementation>b__2(JwtBearerOptions options, IServiceProvider serviceProvider, IOptionsMonitor`1 mergedOptionsMonitor, IOptionsMonitor`1 msIdOptionsMonitor)
   at Microsoft.Extensions.Options.ConfigureNamedOptions`4.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsCache`1.<>c__3`1.<GetOrAdd>b__3_0(String name, ValueTuple`2 arg)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd[TArg](String name, Func`3 createOptions, TArg factoryArgument)
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

```

I cant seem to find the 2.0.5-preview tag to download the source. 

However, as soon as i get a chance, I'll try to get repro if one isn't already tendered

**Comment by Eneuman** [comment]
We have the same issue

**Comment by evandromendonca** [comment]
Hi guys, I am having the same issue here.  Did anyone find something around it?

**Comment by jmprieur** [comment]
@bartdebever, @bartdebever @Eneuman @RbsTechOnline @evandromendonca 
Does one of you has repro steps?

Do you configure claims actions?

**Comment by evandromendonca** [comment]
Hi guys, hi @jmprieur.

Unfortunately, I don't have repo with repro steps. But I could narrow down the issue to Swagger "Swashbuckle.AspNetCore".

The issue was that the `UseSwagger` code must be after the `UseAuthentication` and `UseAuthorization` for some reason. I had it the other way around.

So this did the trick for me:
```csharp
app.UseAuthentication();
app.UseAuthorization();
// and then:
app.UseSwagger();
app.UseSwaggerUI();
```

I didn't have the time to drill down exactly what was causing the issue due to tight deadlines here, but if it is still a thing I can try in the future.

I hope this can help you guys.

Cheers!

**Comment by billyjacobs2014** [comment]
I was experiencing the same problem consistently after upgrading from .net 6 to .net 7. I have a React client with a .net 7 api. When the application loaded the first time by entering in the URL into the browser and hitting the enter key it all worked as expected. If I then click the browser refresh button, I was getting the same error above. As long as I hit the refresh button, I would get the same error. If I typed the url into the address bar and hit enter after it errored, it would work as expected. Not sure why that would trigger the error. 

I then upgraded to Microsoft.Identity.Web 2.0.5-previewand the problem does appear to be resolved as of now.

**Comment by jennyf19** [comment]
Thanks for all the suggestions and repro steps. Does anyone want to see if this [branch](https://github.com/AzureAD/microsoft-identity-web/tree/jennyf/1957) resolves the issue? I'm still working on a repro of the issue.
@RbsTechOnline @billyjacobs2014 @bartdebever @evandromendonca @Eneuman

**Comment by magols** [comment]
> Thanks for all the suggestions and repro steps. Does anyone want to see if this [branch](https://github.com/AzureAD/microsoft-identity-web/tree/jennyf/1957) resolves the issue? 

@jennyf19  I have notable problems with this in development of a Serverside Blazor and and mostly when app is restarted during hot reload.

Using the branch https://github.com/AzureAD/microsoft-identity-web/tree/jennyf/1957 I still have the issue unfortunately.

I am not well versed in this type of code but I noted that the `(!mergedOptions.ClaimActions.Contains(claimAction)) `does not behave as seemingly expected as it will always evaluate to false. There is always a call to Add() duplicates into mergedOptions.ClaimActions. 

As illustrated by this screenshot with duplicate DeleteClaimActions with the same ClaimType and  ValueType.


![image](https://user-images.githubusercontent.com/1081860/201660505-8d171c69-eac4-4a04-9e0c-d1a63685e9c1.png)

**Comment by Eneuman** [comment]
I think contains will check if the exact instance exists in the collection so if any claims mapping has been done, this will probably fail. A more robust implementation would be to check if the claim type and value are the same.

**Comment by jennyf19** [comment]
@magols and @Eneuman the branch has been updated, are the issues resolved? I still cannot manage to repro it, so in order to determine a different fix, I will need clear repro steps. Thanks

**Comment by magols** [comment]
@jennyf19 the good news is that the fix no longer produces an error merging the ClaimsActions here: 
https://github.com/AzureAD/microsoft-identity-web/blob/ecab0d82faba6f866e96e3e8824e29953dc6600d/src/Microsoft.Identity.Web.TokenAcquisition/MergedOptions.cs#L74

The bad news is that we just moved the same type of error to line 214 and the merging of Scopes

https://github.com/AzureAD/microsoft-identity-web/blob/ecab0d82faba6f866e96e3e8824e29953dc6600d/src/Microsoft.Identity.Web.TokenAcquisition/MergedOptions.cs#L210-L216

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Identity.Web.MergedOptions.UpdateMergedOptionsFromMicrosoftIdentityOptions(MicrosoftIdentityOptions microsoftIdentityOptions, MergedOptions mergedOptions) in C:\Source\microsoft-identity-web\src\Microsoft.Identity.Web.TokenAcquisition\MergedOptions.cs:line 212
   at Microsoft.Identity.Web.MicrosoftIdentityOptionsMerger.PostConfigure(String name, MicrosoftIdentityOptions options) in C:\Source\microsoft-identity-web\src\Microsoft.Identity.Web.TokenAcquisition\OptionsMergers\MicrosoftIdentityOptionsMerger.cs:line 19
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsCache`1.<>c__3`1.<GetOrAdd>b__3_0(String name, ValueTuple`2 arg)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd[TArg](String name, Func`3 createOptions, TArg factoryArgument)
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   at Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderExtensions.<>c__DisplayClass5_0.<AddMicrosoftIdentityWebAppInternal>b__3(OpenIdConnectOptions options, IServiceProvider serviceProvider, IOptionsMonitor`1 mergedOptionsMonitor, IOptionsMonitor`1 msIdOptionsMonitor, IOptions`1 msIdOptions) in C:\Source\microsoft-identity-web\src\Microsoft.Identity.Web\WebAppExtensions\MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs:line 287
   at Microsoft.Extensions.Options.ConfigureNamedOptions`5.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsCache`1.<>c__3`1.<GetOrAdd>b__3_0(String name, ValueTuple`2 arg)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd[TArg](String name, Func`3 createOptions, TArg factoryArgument)
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

```

**Comment by magols** [comment]
I think I am able to force the error to occur in a brand new Blazor application. I don't know if this is considered "clear repro steps" but... 

1. Create a new .NET 7 Serverside Blazor app with Microsoft Identity Platform. 
2. Start app in a terminal with dotnet watch run, preferably with a few duplicate browser tabs opened. (I have one Incognito window logged in also)
3. In terminal press Ctrl-R to restart application and to reload tabs. It won't crash every time but usually after a few (4-5) restarts the error will occur in at least one of the browser tabs.

**Comment by jennyf19** [comment]
@magols Those steps helped a lot. I have updated the branch.

**Comment by jmprieur** [comment]
@billyjacobs2014 what do you mean not on a branch? It's in [jennyf/fix1957](https://github.com/AzureAD/microsoft-identity-web/tree/jennyf/fix1957)

**Comment by jennyf19** [comment]
The issue is fixed in [1.25.6](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.25.6) based on the repro provided by @magols.

**Comment by jennyf19** [comment]
Going to reopen, as I need to apply to rel/v2 and release there as well.

**Comment by magols** [comment]
Using the  https://github.com/AzureAD/microsoft-identity-web/tree/jennyf/fix1957 branch I still sometimes get the error from line 214. 

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
         at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
         at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
         at Microsoft.Identity.Web.MergedOptions.UpdateMergedOptionsFromMicrosoftIdentityOptions(MicrosoftIdentityOptions microsoftIdentityOptions, MergedOptions mergedOptions) in C:\Source\microsoft-identity-web\src\Microsoft.Identity.Web.TokenAcquisition\MergedOptions.cs:line 214
         at Microsoft.Identity.Web.MicrosoftIdentityOptionsMerger.PostConfigure(String name, MicrosoftIdentityOptions options) in C:\Source\microsoft-identity-web\src\Microsoft.Identity.Web.TokenAcquisition\OptionsMergers\MicrosoftIdentityOptionsMerger.cs:line 19
         at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
         at Microsoft.Extensions.Options.OptionsCache`1.<>c__3`1.<GetOrAdd>b__3_0(String name, ValueTuple`2 arg)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
         at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd[TArg](String name, Func`3 createOptions, TArg factoryArgument)
         at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
         at Microsoft.Identity.Web.MicrosoftIdentityWebAppAuthenticationBuilderExtensions.<>c__DisplayClass5_0.<AddMicrosoftIdentityWebAppInternal>b__3(OpenIdConnectOptions options, IServiceProvider serviceProvider, IOptionsMonitor`1 mergedOptionsMonitor, IOptionsMonitor`1 msIdOptionsMonitor, IOptions`1 msIdOptions) in C:\Source\microsoft-identity-web\src\Microsoft.Identity.Web\WebAppExtensions\MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs:line 287
         at Microsoft.Extensions.Options.ConfigureNamedOptions`5.Configure(String name, TOptions options)
         at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
         at Microsoft.Extensions.Options.OptionsCache`1.<>c__3`1.<GetOrAdd>b__3_0(String name, ValueTuple`2 arg)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
         at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd[TArg](String name, Func`3 createOptions, TArg factoryArgument)
         at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
         at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

```

**Comment by bartdebever** [comment]
Unfortunately, I'm still getting the same error using version 1.25.6 but only if there are multiple requests going to the API.
If I use Swagger to do a single request the exception does not occur, if I let the frontend do the first requests, the exception occurs twice.

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()                                                                                                                                                                                                                                                                
System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
at Microsoft.Identity.Web.MergedOptions.UpdateMergedOptionsFromMicrosoftIdentityOptions(MicrosoftIdentityOptions microsoftIdentityOptions, MergedOptions mergedOptions)
at Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderExtensions.<>c__DisplayClass3_0.<AddMicrosoftIdentityWebApiImplementation>b__0(JwtBearerOptions options, IServiceProvider serviceProvider, IOptionsMonitor`1 mergedOptionsMonitor, IOptionsMonitor`1 msIdOptionsMonitor, IOptions`1 msIdOptions)
at Microsoft.Extensions.Options.ConfigureNamedOptions`5.Configure(String name, TOptions options)
at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
at Microsoft.Extensions.Options.OptionsCache`1.<>c__3`1.<GetOrAdd>b__3_0(String name, ValueTuple`2 arg)
at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)                                                                                                                                                                                                 
at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd[TArg](String name, Func`3 createOptions, TArg factoryArgument)
at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)   
at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context) 
```

**Comment by MGD-dev** [comment]
I was having the same issue on my API for a Blazor WASM project after updating to .net 7.
Oddly enough I had updated 2 projects and only 1 was having the issue. 
The project that was not having the issue makes a single API call on startup before any other calls can be made to gather user permissions. 
For me and as @magols stated it seems the issue occurs when multiple API calls are made on startup. 
I updated the 2nd project to make the single service call before any others could be made and it fixed the issue.

**Comment by jmprieur** [comment]
We believe we have a fix, which we'll release tomorrow PST.

**Comment by jennyf19** [comment]
+1 to @f1nzer

**Comment by jennyf19** [comment]
1.25.7 is released. We will release the fix in v2-preview as well.

**Comment by f1nzer** [comment]
@jennyf19 @jmprieur 
Unfortunately, the issue was not fixed. The problem might be reproduced on the same test using v1.25.8, just run it a couple of times.
Stacktrace:
```
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location)
   at System.Collections.Generic.HashSet`1.System.Collections.Generic.ICollection<T>.Add(T item)
   at Microsoft.Identity.Web.MergedOptions.UpdateMergedOptionsFromMicrosoftIdentityOptions(MicrosoftIdentityOptions microsoftIdentityOptions, MergedOptions mergedOptions)
   at Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderExtensions.<>c__DisplayClass3_0.<AddMicrosoftIdentityWebApiImplementation>b__0(JwtBearerOptions options, IServiceProvider serviceProvider, IOptionsMonitor`1 mergedOptionsMonitor, IOptionsMonitor`1 msIdOptionsMonitor, IOptions`1 msIdOptions)
   at Microsoft.Extensions.Options.ConfigureNamedOptions`5.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsCache`1.<>c__3`1.<GetOrAdd>b__3_0(String name, ValueTuple`2 arg)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd[TArg](String name, Func`3 createOptions, TArg factoryArgument)
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by jmprieur** [comment]
which same test? you mean the unit test? or the test with dotnet watch?

**Comment by slubowsky** [comment]
@jennyf19 @jmprieur Just FYI, in my API, it used to happen (beginning after upgrade to .NET 7) every time it started up (when hit first from web app - multiple connections at once, no issues when hit first from single swagger connection, as documented [above](https://github.com/AzureAD/microsoft-identity-web/issues/1957#issuecomment-1316707427))
Using 2.0.6-preview, it now works about 50% of the time. So not sure if that's better or worse, but clearly there is still a problem.

```
System.InvalidOperationException: 'Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.'

This exception was originally thrown at this call stack:
    System.ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported() in ThrowHelper.cs
    System.Collections.Generic.HashSet<T>.AddIfNotPresent(T, out int) in HashSet.cs
    System.Collections.Generic.HashSet<T>.System.Collections.Generic.ICollection<T>.Add(T) in HashSet.cs
    Microsoft.Identity.Web.MergedOptions.UpdateMergedOptionsFromMicrosoftIdentityOptions(Microsoft.Identity.Web.MicrosoftIdentityOptions, Microsoft.Identity.Web.MergedOptions) in MergedOptions.cs
    Microsoft.Identity.Web.MicrosoftIdentityOptionsMerger.PostConfigure(string, Microsoft.Identity.Web.MicrosoftIdentityOptions) in MicrosoftIdentityOptionsMerger.cs
    Microsoft.Extensions.Options.OptionsFactory<TOptions>.Create(string) in OptionsFactory.cs
    Microsoft.Extensions.Options.OptionsCache<TOptions>.GetOrAdd.AnonymousMethod__3_0(string, (System.Func<string, TArg, TOptions> createOptions, TArg factoryArgument)) in OptionsCache.cs
    System.Collections.Concurrent.ConcurrentDictionary<TKey, TValue>.GetOrAdd<TArg>(TKey, System.Func<TKey, TArg, TValue>, TArg) in ConcurrentDictionary.cs
    Microsoft.Extensions.Options.OptionsCache<TOptions>.GetOrAdd<TArg>(string, System.Func<string, TArg, TOptions>, TArg) in OptionsCache.cs
    Microsoft.Extensions.Options.OptionsMonitor<TOptions>.Get(string) in OptionsMonitor.cs
    ...
    [Call Stack Truncated]
```

**Comment by f1nzer** [comment]
> which same test @f1nzer? you mean the unit test? or the test with dotnet watch?

It can be reproduced with the same unit test I sent you before.

**Comment by jennyf19** [comment]
@f1nzer we have a fix in master now, I'm not able to repro it with the test you provided, even with 100k concurrent calls.

**Comment by bartdebever** [comment]
I want to confirm that as of the latest release (1.25.9), this issue has indeed been fixed and working in a production scenario.

**Comment by jmprieur** [comment]
Thanks for confirming @bartdebever 
and thanks everybody for your help!

**Comment by petedishman** [comment]
The linked merged request #1979 is still open and not merged to master yet? And the source code download for the 1.25.9 release doesn't show it either.

Has this actually not been resolved in the latest nuget release or have I misunderstood something?

**Comment by jmprieur** [comment]
the .NET 7 fix should be released mid February.
Meanwhile, a workaround is described here: https://github.com/AzureAD/microsoft-identity-web/issues/1995#issuecomment-1374281775

**Comment by rondelward-pf** [comment]
Thanks @jmprieur, I'll implement the suggested workaround for now. Will the fix also make it to the LTS .NET6 version as well? I thought it was a package problem not in the runtime but just curious if I need to wait for .NET7 or 8 to remove the workaround.

**Comment by jmprieur** [comment]
@rondelward-pf : it's a regression in .NET 7.
So I believe the next runtime patch of .NET 7 should fix it.

**Comment by AndreErb** [comment]
@jmprieur
We're still seeing this in multiple APIs, though using "Microsoft.Identity.Web" V2.13.4
Also, we are using .NET 6, only.
 
You wrote, that's a regression in .NET 7, but you did not specifically anwser the question of @rondelward-pf, [if this fixes it for .NET 6, too](https://github.com/AzureAD/microsoft-identity-web/issues/1957#issuecomment-1412767721) .

What confuses me too, is that the [Fix](https://github.com/AzureAD/microsoft-identity-web/pull/1979/commits/b13f8c7ebe500528687eab720e8ea8802f2d2b7b) was made in "Microsoft.Identity.Web", so why did you point out the next .NET 7 runtime patch? Shouldn't the [commit](https://github.com/AzureAD/microsoft-identity-web/pull/1979/commits/b13f8c7ebe500528687eab720e8ea8802f2d2b7b) fix it by itself?

> So I believe the next runtime patch of .NET 7 should fix it.

This is one of these log entries, using V2.13.4

`2023-09-21T13:07:16.4158570+02:00 [Thread:] [ERR] (Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer) Connection ID ""5188146776636391632"", Request ID ""800000d1-0001-4800-b63f-84710c7967bb"": An unhandled exception was thrown by the application.
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location)
   at System.Collections.Generic.HashSet`1.System.Collections.Generic.ICollection<T>.Add(T item)
   at Microsoft.Identity.Web.MergedOptions.UpdateMergedOptionsFromMicrosoftIdentityOptions(MicrosoftIdentityOptions microsoftIdentityOptions, MergedOptions mergedOptions)
   at Microsoft.Identity.Web.MicrosoftIdentityOptionsMerger.PostConfigure(String name, MicrosoftIdentityOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsMonitor`1.<>c.<Get>b__10_0(String name, IOptionsFactory`1 factory)
   at Microsoft.Extensions.Options.OptionsCache`1.<>c__3`1.<GetOrAdd>b__3_0(String name, ValueTuple`2 arg)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd[TArg](String name, Func`3 createOptions, TArg factoryArgument)
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   at Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderExtensions.<>c__DisplayClass3_0.<AddMicrosoftIdentityWebApiImplementation>b__2(JwtBearerOptions options, IServiceProvider serviceProvider, IMergedOptionsStore mergedOptionsMonitor, IOptionsMonitor`1 msIdOptionsMonitor)
   at Microsoft.Extensions.Options.ConfigureNamedOptions`4.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsMonitor`1.<>c.<Get>b__10_0(String name, IOptionsFactory`1 factory)
   at Microsoft.Extensions.Options.OptionsCache`1.<>c__3`1.<GetOrAdd>b__3_0(String name, ValueTuple`2 arg)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd[TArg](String name, Func`3 createOptions, TArg factoryArgument)
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatcher|8_0(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task`1 matcherTask)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()`

**Comment by Bigcountry409** [comment]
> @rondelward-pf : it's a regression in .NET 7.
> 
> So I believe the next runtime patch of .NET 7 should fix it.

Man, I know this ain't in there about anything that you're researching are done, but my cell phone got hacked into three days ago from some kind of Greek website of Telegram and somebody's been looking up stuff that I don't even recognize on my history wall. Is there anyway you could try to look into it for me and see what the hell is going on cause I just bought his damn phone And fixing you get 15 promax but I don't wanna do nothing they're gonna get into it like it is there anyway you can check it out for me please my number is 423-912-0506 and my name is Norman
