### ISSUE TITLE
Load Certs from keyVault using managedIdentity for client Credentials

### ISSUE THREAD

**Issue by sdivi** [AzureAD/microsoft-identity-web#2311]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.12.2

### Web app

Sign-in users

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

In-memory caches

### Description

I have an Azure Ad config that has configuration defined for clientCertificates and the certificate source is keyVault.

It works fine with default credentials. When trying to load certs using managedIdentity to talk to keyVault by specifying UserAssignedManagedIdentityId it doesn't work

### Reproduction steps

Create a sample web api that uses clientCerts to generate a token to talk to keyVault . 

Seems like v2.0 broke this. It is working fine with versions < 2.0 tried with 1.25.10

### Error message

System.ArgumentException: IDW10109: All client certificates passed to the configuration have expired or can't be loaded. (Parameter 'clientCredentials')
at Microsoft.Identity.Web.ConfidentialClientApplicationBuilderExtension.WithClientCredentials(ConfidentialClientApplicationBuilder builder, IEnumerable`1 clientCredentials, ILogger logger, ICredentialsLoader credentialsLoader, CredentialSourceLoaderParameters credentialSourceLoaderParameters)
at Microsoft.Identity.Web.TokenAcquisition.BuildConfidentialClientApplication(MergedOptions mergedOptions)
at Microsoft.Identity.Web.TokenAcquisition.GetOrBuildConfidentialClientApplication(MergedOptions mergedOptions)
at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForUserAsync(IEnumerable`1 scopes, String authenticationScheme, String tenantId, String userFlow, ClaimsPrincipal user, TokenAcquisitionOptions tokenAcquisitionOptions)
at Microsoft.Identity.Web.TokenAcquisition.GetAccessTokenForUserAsync(IEnumerable`1 scopes, String authenticationScheme, String tenantId, String userFlow, ClaimsPrincipal user, TokenAcquisitionOptions tokenAcquisitionOptions)

### Relevant code snippets

```csharp
I don't see mergedOptions copying over the property from identityOptions UserAssignedManagedIdentityId

https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web.TokenAcquisition/MergedOptions.cs
```

### Regression

1.25.10

### Expected behavior

Able to load certs from keyVault utilizing managedIdentity

**Comment by simonschlegel** [comment]
I am having a similar issue with App Service Webjobs. It would be helpful if this error is logged when credential type is certificate https://github.com/AzureAD/microsoft-identity-web/blob/e528daa928b51c8f313cccc72c6f9967e936107b/src/Microsoft.Identity.Web.TokenAcquisition/ConfidentialClientApplicationBuilderExtension.cs#L38C51-L38C51.

**Comment by bradhugh** [comment]
Also having this same problem. There's no logging or tracing in the Key Vault certificate loader so it's impossible to know why it's not working

**Comment by bjwilsonPCX** [comment]
We recently tried to update a couple of our API's to use Microsoft.Identity.Web 2.19.1 and experienced similar issues.  We tried it with both ClientCertificates with CertificateDescription and ClientCredentials with CredentialDescription and both failed with similar errors.  Thanks.

**Comment by jmprieur** [comment]
Do you have repro steps?

**Comment by bradhugh** [comment]
I actually found that updating to the latest version of Microsoft.Identity.Web solved my issue. It had to do with proper detection of the AZURE_CLIENT_ID environment variable if my memory serves me.

**Comment by bjwilsonPCX** [comment]
@bradhugh - any chance you could elaborate a bit on your AZURE_CLIENT_ID comments?

@jmprieur - I'm in the middle of something else right now, but I'll try to post my repro steps here in the next day or two.

**Comment by bjwilsonPCX** [comment]
Greetings, so I was tasked with updating the Microsoft.Identity.Web library for some BAU work we are doing.  Previously it was at 1.24.1.  This backend API (our top layer) is connecting with another backend API that is specifically used for storing documents to Containers in an Azure Storage account. Our existing Startup.cs code (the names have been changed where applicable to protect the innocent) is:

```
                services
                    .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                    .AddMicrosoftIdentityWebApi(options => { }, options =>
                    {
                        options.Instance = "REDACTED";
                        options.TenantId = "REDACTED";
                        options.ClientId = "REDACTED";
                        options.UserAssignedManagedIdentityClientId = "REDACTED";
                        options.ClientCertificates = new CertificateDescription[]
                        {
                            CertificateDescription.FromKeyVault(keyVaultUri, "REDACTED")
                        };
                    })
                    .EnableTokenAcquisitionToCallDownstreamApi((_) => { })
                    .AddDownstreamWebApi("ThatDocsService", Configuration.GetSection("ThatDocsService"))
                    // Enabling the in-memory token cache will allow the JWT access tokens to be cached and used (until a token expires)
                    .AddInMemoryTokenCaches();
```
					
This code is working in all of our environments.  After updating to 2.19.1 I went through these links trying to make sure I covered my bases.
* https://github.com/AzureAD/microsoft-identity-web/wiki/v2.0
* https://github.com/AzureAD/microsoft-identity-web/releases
* https://github.com/AzureAD/microsoft-identity-web/blob/master/docs/blog-posts/downstreamwebapi-to-downstreamapi.md

```
"ThatDocsService": {
    "BaseUrl": "REDACTED URL",
    "Scopes": [
      "REDACTED URL"
    ]
  }
```

```
                services
                    .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                    .AddMicrosoftIdentityWebApp(microsoftIdentityOptions =>
                    {
                        Configuration.Bind("AzureAd", microsoftIdentityOptions);
                        microsoftIdentityOptions.Instance = "REDACTED";
                        microsoftIdentityOptions.TenantId = "REDACTED";
                        microsoftIdentityOptions.ClientId = "REDACTED";
                        microsoftIdentityOptions.UserAssignedManagedIdentityClientId = "REDACTED";
                        microsoftIdentityOptions.ClientCredentials = new CredentialDescription[]
                        {
                            new CredentialDescription() {
                                SourceType = CredentialSource.KeyVault,
                                KeyVaultCertificateName = "REDACTED",
                                KeyVaultUrl = keyVaultUri
                            }
                        };
                    })
                    .EnableTokenAcquisitionToCallDownstreamApi(new string[] { "" })
                    .AddDownstreamApi("ThatDocsService", Configuration.GetSection("ThatDocsService"))
                    // Enabling the in-memory token cache will allow the JWT access tokens to be cached and used (until a token expires)
                    .AddInMemoryTokenCaches();
```
					
With this code I'm seeing a lot of this when attempting to connect to the downstream API:
```
 InnerException: { 
       HResult: -2147024809
       Message: IDW10109: All client certificates passed to the configuration have expired or can't be loaded.  (Parameter 'clientCredentials')
       ParamName: clientCredentials
       Source: Microsoft.Identity.Web.TokenAcquisition
       StackTrace:    at Microsoft.Identity.Web.ConfidentialClientApplicationBuilderExtension.WithClientCredentialsAsync(ConfidentialClientApplicationBuilder builder, IEnumerable`1 clientCredentials, ILogger logger, ICredentialsLoader credentialsLoader, CredentialSourceLoaderParameters credentialSourceLoaderParameters)
   at Microsoft.Identity.Web.TokenAcquisition.BuildConfidentialClientApplicationAsync(MergedOptions mergedOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetOrBuildConfidentialClientApplicationAsync(MergedOptions mergedOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForAppAsync(String scope, String authenticationScheme, String tenant, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Microsoft.Identity.Web.DefaultAuthorizationHeaderProvider.CreateAuthorizationHeaderForAppAsync(String scopes, AuthorizationHeaderProviderOptions downstreamApiOptions, CancellationToken cancellationToken)
   at Microsoft.Identity.Web.DownstreamApi.UpdateRequestAsync(HttpRequestMessage httpRequestMessage, HttpContent content, DownstreamApiOptions effectiveOptions, Boolean appToken, ClaimsPrincipal user, CancellationToken cancellationToken)
   at Microsoft.Identity.Web.DownstreamApi.CallApiInternalAsync(String serviceName, DownstreamApiOptions effectiveOptions, Boolean appToken, HttpContent content, ClaimsPrincipal user, CancellationToken cancellationToken)
```

We'll give the updated AZURE_CLIENT_ID environment variable a try in the near future too.

**Comment by bradhugh** [comment]
@bjwilsonPCX - From what I can remember, the version I was using wasn't properly reading the AZURE_CLIENT_ID variable even though it was defined. We have a user-assigned managed identity, so it was necessary to specify this, but even with it specified, it seemed to not be using it to attempt to access the key vault. There have been some changes in the code in this area, so when I realized I wasn't on the latest version, I updated and the problem was resolved. According to my source history, the version I was using that had the problem was 2.13.4 and the version that I updated to was 2.17.1.

**Comment by oakular** [comment]
We are also experiencing this on v2.19.1, for key vault and local certs. I have not yet tried downgrading as we can use the client secret as a workaround for now.

**Comment by kipkoei** [comment]
We are still experiencing this on v3.1.0. We're using System assigned managed identity (so AZURE_CLIENT_ID should not be necessary). The managed identity has the Key Vault Certificate User Role and the certificate is still valid for a long time (it works locally, without the Key Vault). Any help would be greatly appreciated.

Our configuration and setup looks like this.
appsettings.json
```json
{
    "MicrosoftEntraID": {
        "Instance": "https://login.microsoftonline.com/",
        "TenantId": "<TENANT>",
        "ClientId": "<CLIENT>",
        "Scopes": ".default",
        "ClientCertificates": [
            {
                "SourceType": "KeyVault",
                "KeyVaultUrl": "<URI>",
                "KeyVaultCertificateName": "<NAME>"
            }
        ]
    }
}
```

program.cs
```csharp
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApi(builder.Configuration, "MicrosoftEntraID")
                .EnableTokenAcquisitionToCallDownstreamApi()
                .AddMicrosoftGraph(options => options.RequestAppToken = true)
                .AddInMemoryTokenCaches();
```

**Comment by BernieEllis** [comment]
@jmprieur any comments on this? @kipkoei are you still experiencing this issue?

I'm seeing this issue with Microsoft.Identity.Web v3.2.2.

Very similar behavior to @kipkoei where I'm not seeing the issue locally. I'm trying to retrieve a certificate from Key Vault for a .NET 8 web api to make downstream calls to either Microsoft Graph or ARM. This is in Azure App Service with a **system** assigned identity enabled, with the appropriate access to Azure Key Vault. This is proven

Dev Config (appsettings.Dev.Json) - This works

"EntraIdDev": {
  "Instance": "https://login.microsoftonline.com/",
  "Domain": "REDACTED",
  "TenantId": "REDACTED",
  "ClientId": "REDACTED",
  "ClientCertificates": [
    {
      "SourceType": "Path",
      "CertificateDiskPath": "REDACTED",
      "CertificatePassword": "REDACTED!"
    }
  ],
  "ValidateAuthority": true,
  "ValidIssuer": "https://sts.windows.net/REDACTED/",
  "Scopes": [ "api://REDACTED/api.access" ]
},

Prod Config is largely the same as dev, except two things:

1. Pulling config from Azure App Configuration
2. Certificate is in Key Vault vs. local disk.

The documentation flips between EntraId:ClientCredentials vs. EntraId:ClientCertificates so I have both specified in config.

This fails, and the error I receive is:

Exception: 
System.ArgumentException: IDW10109: No credential could be loaded. This can happen when certificates passed to the configuration have expired or can't be loaded and the code isn't running on Azure to be able to use Managed Identity, Pod Identity etc. Details: 
 (Parameter 'clientCredentials')
   at Microsoft.Identity.Web.ConfidentialClientApplicationBuilderExtension.LoadCredentialForMsalOrFailAsync(IEnumerable`1 clientCredentials, ILogger logger, ICredentialsLoader credentialsLoader, CredentialSourceLoaderParameters credentialSourceLoaderParameters)
   at Microsoft.Identity.Web.ConfidentialClientApplicationBuilderExtension.WithClientCredentialsAsync(ConfidentialClientApplicationBuilder builder, IEnumerable`1 clientCredentials, ILogger logger, ICredentialsLoader credentialsLoader, CredentialSourceLoaderParameters credentialSourceLoaderParameters)
   at Microsoft.Identity.Web.TokenAcquisition.BuildConfidentialClientApplicationAsync(MergedOptions mergedOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetOrBuildConfidentialClientApplicationAsync(MergedOptions mergedOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForUserAsync(IEnumerable`1 scopes, String authenticationScheme, String tenantId, String userFlow, ClaimsPrincipal user, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetAccessTokenForUserAsync(IEnumerable`1 scopes, String authenticationScheme, String tenantId, String userFlow, ClaimsPrincipal user, TokenAcquisitionOptions tokenAcquisitionOptions)

I'm following the guidance from https://github.com/AzureAD/microsoft-identity-web/wiki/Certificates#client-certificates. I've tried defining via configuration and programmatically.

**Comment by BernieEllis** [comment]
Ok, I believe I have the cause of this, at least for my scenario. I have a certificate stored in Key Vault for my web api that I'll use to authenticate to Microsoft Graph and EntraId to perform downstream calls to ARM on behalf of users, so I needed this same certificate for two different use cases. When I tried making calls to Graph, I received this error:

Exception: 
System.Exception: MSGraphServiceErro: Error searching users
 ---&gt; Azure.Identity.AuthenticationFailedException: ClientCertificateCredential authentication failed: The certificate certificate does not have a private key. 
 ---&gt; MSAL.NetCore.4.65.0.0.MsalClientException:
	ErrorCode: cert_without_private_key

### Root Cause

**The root cause is the certificate is being retrieved from Key Vault without the private key**. While Microsoft.Identity.Web gave a generic/ambiguous error, MS Graph gave the specific reason for not being able to load/use the cert being retrieved from Key Vault.

**When did this happen/repro scenario?**

This is when specifying either ClientCredentials or ClientCertificates in configuration with only the Key Vault Url and Key Vault Certificate Name.

**Original Key Vault Certificate Fetch for Graph Client (No Private Key Retrieved)**:

```
var keyVaultUrl = new Uri(builder.Configuration["KeyVault:Url"]);
var apiCertificateName = builder.Configuration["KeyVault:Certificates:MyAPI"];

var certificateClient = new CertificateClient(keyVaultUrl, new DefaultAzureCredential());
KeyVaultCertificateWithPolicy apiCertificateRequest = await certificateClient.GetCertificateAsync(apiCertificateName);

var apiCertificate = new X509Certificate2(apiCertificateRequest.Cer);

var graphCredential = new ClientCertificateCredential(tenantId, clientId, apiCertificate);
var graphServiceClient = new GraphServiceClient(graphCredential, graphScopes);

builder.Services.AddSingleton(graphServiceClient);
```

**Corrected Key Vault Certificate Fetch with Private Key**:

```
var keyVaultUrl = new Uri(builder.Configuration["KeyVault:Url"]);
var apiCertificateName = builder.Configuration["KeyVault:Certificates:MyAPI"];

//Use SecretClient instead of CertificateClient
var secretClient = new SecretClient(keyVaultUrl, new DefaultAzureCredential());

// Retrieve the certificate secret (includes private key)
KeyVaultSecret certificateSecret = await secretClient.GetSecretAsync(apiCertificateName);

byte[] privateKeyBytes = Convert.FromBase64String(certificateSecret.Value);

// Load the certificate with the private key
var apiCertificate = new X509Certificate2(privateKeyBytes, (string)null, X509KeyStorageFlags.MachineKeySet);

var graphCredential = new ClientCertificateCredential(tenantId, clientId, apiCertificate);
var graphServiceClient = new GraphServiceClient(graphCredential, graphScopes);

builder.Services.AddSingleton(graphServiceClient);
```

### How does this relate back to setting up authentication with EntraId?

**Original Web API Authentication Setup**:

Below is what I was originally using to add web api authentication, using the minimal method Microsoft is now recommending. Note that I have the KeyVault Url and Certificate Name specified in Config (via Azure App Configuration in my case). I'm letting Microsoft.Identity.Web handle retrieving the certificate from KeyVault per Microsoft Identity documentation guidance.

This fails, results in IDW10109 credential loading error.
```
builder.Services.AddMicrosoftIdentityWebApiAuthentication(builder.Configuration, "EntraId", JwtBearerDefaults.AuthenticationScheme, subscribeToJwtBearerMiddlewareDiagnosticsEvents: true)
    .EnableTokenAcquisitionToCallDownstreamApi()
    .AddInMemoryTokenCaches();
```

**Corrected Web Api Authentication Setup**:

I'm still retrieving the certificate from Key Vault using the code above in the "Corrected Key Vault Certificate Fetch with Private Key" section above. The difference is I'm passing the certificate already retrieved from Key Vault to the method.

```
 builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApi(
         configureJwtBearerOptions =>
         {
            builder.Configuration.Bind("EntraId", configureJwtBearerOptions);
         },
         microsoftIdentityOptions =>
         {
             builder.Configuration.Bind("EntraId", microsoftIdentityOptions);
             microsoftIdentityOptions.ClientCertificates = new CertificateDescription[] {
                         CertificateDescription.FromCertificate(apiCertificate) //Same Certificate retrieved in the Graph setup above.
             };
         })
    .EnableTokenAcquisitionToCallDownstreamApi(
         confidentialClientApplicationOptions =>
         {
             builder.Configuration.Bind("EntraId", confidentialClientApplicationOptions);
         })
    .AddInMemoryTokenCaches();
```

For the record, I did test and confirm that CertificateDescription.FromKeyVault also works:

```
microsoftIdentityOptions =>
{
     builder.Configuration.Bind("EntraId", microsoftIdentityOptions);
     microsoftIdentityOptions.ClientCertificates = new CertificateDescription[] {
                 CertificateDescription.FromKeyVault(keyVaultUrl.ToString(), apiCertificateName)
     };
})
```

### My Takeaways

1. I guess I was lucky in finding the cause from Microsoft Graph but it's not ideal having to rely on interacting with another service to get a descriptive enough error condition to understand what was going on. This had me stumped, had no clue the certificate was being retrieved from Key Vault without the private key. Microsoft.Identity.Web and/or MSAL exception logging could use an update.
2. For whatever reason neither builder.Services.AddAuthentication.AddMicrosoftIdentityWebApi  builder.Services.AddMicrosoftIdentityWebApiAuthentication method can properly take a Key Vault Url and certificate name and convert that into a usable certificate credential (with private key) for token acquisition.
3. Use CertificateDescription.FromKeyVault or CertificateDescription.FromCertificate methods. With the latter, be sure you have private key access.

Hope this helps someone,
Bernie
