### ISSUE TITLE
AccountController implementing MicrosoftIdentity/Account/xxx endpoints does not honour redirectUrl

### ISSUE THREAD

**Issue by rollandjb** [AzureAD/microsoft-identity-web#760]
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 
Microsoft Identity Web 1.2.0

**Where is the issue?**
* Web app
    * [x] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
This is an app in development

**Repro**

```html
<a href="MicrosoftIdentity/Account/SignIn?redirectUrl=yyy">Sign In</a>
```

**Expected behavior**
Clicking on the link should take me to the page at `yyy`

**Actual behavior**
Takes me to the route of the application, `/`

**Possible solution**
Set the `redirectUrl` property of AuthenticationProperties to the incoming query value

```csharp
[HttpGet("{scheme?}/{redirectUrl?}")]
        public IActionResult SignIn([FromRoute] string scheme, [FromQuery] string redirectUrl)
        {
            scheme ??= OpenIdConnectDefaults.AuthenticationScheme;
            // var redirectUrl = Url.Content("~/");
            return Challenge(
                new AuthenticationProperties { RedirectUrl = redirectUrl ?? Url.Content("~/") },
                scheme);
        }
```

All endpoints should honour `redirectUrl`

**Additional context / logs / screenshots**

This will allow clients to use `MicrosoftIdentity/Account/xxx` endpoints and land the user on desired page.

**Comment by jmprieur** [comment]
Thanks for the heads-up @rollandjb

**Comment by rollandjb** [comment]
My pleasure @jmprieur

**Comment by jmprieur** [comment]
@rollandjb I tried to repro this bug, but cannot.
Using https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/B2CWebAppCallsWebApi, and signing out each time, I'm always redirected to the page where the sign-in was triggered.

Do you have repro steps? Do you want to force another redirect URL?

**Comment by rollandjb** [comment]
@jmprieur 

I don't know ASP.NET Core web apps well enough to know how the page url is being remembered.

In the case of a SPA hosted on the web app, one would need to specify the `redirectUrl` as a query parameter:

    <a href="/MicrosoftIdentity/Account/SignIn?redirectUrl=/pages/products">Sign In</a>

`AuthentcationProperties` provides the mechanism to specify such a location using the `RedirectUri` property. It would be helpful if the `/MicrosoftIdentity/Account/` controller would support that.

The alternative is for me to implement my own endpoints. I would have to reroute those that are hard coded into the `AzureADB2COpenIdConnectEventHandlers` to my implementations. This is totally doable; it just seems better to use the built-in ones.

What do you think?

**Comment by jennyf19** [comment]
moving to another iteration, as we need to update the templates as well and requires more time on our end to understand how to support this better & test.

**Comment by darraghjones** [comment]
Yeah, i don't understand why the RedirectUrl is hard-coded to "~/" here: https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web.UI/Areas/MicrosoftIdentity/Controllers/AccountController.cs#L46

what if i want to redirect to a different page in my web app after logging in?

**Comment by jennyf19** [comment]
@darraghjones @rollandjb fix has been merged into master. will be in next release.

**Comment by jmprieur** [comment]
@darraghjones @rollandjb: released in 1.12.0

**Comment by AndreyZ1** [comment]
@jmprieur hey here, could you help me, please, I just updated version but seems it's not working, am I doing something wrong?

`<a asp-area="MicrosoftIdentity" asp-route-redirectUri="@Model.ReturnUrl" asp-controller="Account" asp-action="SignIn">Sign in with Microsoft</a>`

**Comment by jmprieur** [comment]
@AndreyZ1 : I'm not sure about the asp-route-redirectUri notation (I'm not familiar with it). Where is it documented?

We used:

```html
<a href="/MicrosoftIdentity/Account/SignIn?redirectUri=/TodoList">Sign In</a>
```

Maybe make sure that `@Model.ReturnUrl` starts by a / ?

**Comment by AndreyZ1** [comment]
@jmprieur Just tried to use hardcoded link
`<a href="/MicrosoftIdentity/Account/SignIn?redirectUri=/TodoList">Sign In</a>`
and it still not working. Do I have to enable something in Startup.cs configuration or somewhere else to make it working?

**Comment by jmprieur** [comment]
No @AndreyZ1 
The devapp with which this was tested is here:
https://github.com/AzureAD/microsoft-identity-web/blob/b348c484aa0a86c460f99e36a8775ac6bc240269/tests/WebAppCallsWebApiCallsGraph/Client/Views/Shared/_LoginPartial.cshtml#L12

just update Microsoft.Identity.Web and Microsoft.Identity.Web.UI

**Comment by AndreyZ1** [comment]
@jmprieur thank you a lot for help, I updated only Microsoft.Identity.Web and forgot about Microsoft.Identity.Web.UI.

**Comment by jmprieur** [comment]
Thanks for the update, @AndreyZ1 
Does it work with the `asp-route-redirectUri="@Model.ReturnUrl"` form?

**Comment by AndreyZ1** [comment]
@jmprieur yes, without any problems.

**Comment by jeevanthespark** [comment]
I am not sure what was fixed in earlier builds but I still can't make it work. The code is very simple as given below.

```
<form method="get" asp-area="MicrosoftIdentity" asp-controller="Account" asp-action="SignIn" asp-route-redirectUri="/Claims">
                <button type="submit" class="btn btn-primary">Sign In</button>
</form>
```

Can anyone please help to fix the issue?

**Comment by jmprieur** [comment]
@jeevanthespark : did you try with:

```xml
<li><a href="/MicrosoftIdentity/Account/SignIn?redirectUri=/Claims">Sign In</a></li> 
```

**Comment by jeevanthespark** [comment]
Yes, I did. Finally I fixed it by adding app.MapControllers which was missed and no documentation explains it needs to be added to middleware. Could you please update the documentation?
